In [1]:
import numpy as np

vect = np.random.randn(4, 3)

array([[-1.06338551,  0.27678748, -0.26203555],
       [ 0.59882692, -0.01301252,  0.48442794],
       [-0.18736234,  0.64305756, -1.46516338],
       [ 1.6101792 , -1.07688552,  1.8326678 ]])

In [3]:
vect.sum()

1.3781020769003915

In [30]:
a[0][1]

array([[-1.02547828, -0.68208453,  0.90326895],
       [-0.19209147, -0.98852061,  0.40763643]])

In [19]:
a = np.random.randn(4, 3, 2, 3)
a

array([[[[ 0.48919425,  1.09841711,  0.20899724],
         [-1.10105209,  1.05821219, -1.32661322]],

        [[-1.02547828, -0.68208453,  0.90326895],
         [-0.19209147, -0.98852061,  0.40763643]],

        [[ 0.5955812 ,  0.1459882 , -1.41524583],
         [-1.02023904, -2.33976778, -1.52018717]]],


       [[[-0.56686845,  1.29022951, -0.68805121],
         [ 1.12494808,  0.69039012,  0.47913708]],

        [[-2.37307721, -0.11113159, -1.20162946],
         [ 0.53142045, -0.07236708, -0.33296522]],

        [[-1.60191159,  0.42825722,  0.46601253],
         [ 0.24798787, -0.27410323,  0.57664818]]],


       [[[-2.44163023, -0.55672005,  0.97552243],
         [-1.08617604,  1.68863399, -1.23893593]],

        [[-0.56714872, -2.60786517, -0.2868573 ],
         [-0.7509293 , -0.21987761, -1.29013856]],

        [[-1.6175755 ,  0.38669742, -1.49516612],
         [-0.92311524,  0.78293493, -0.68936009]]],


       [[[-0.55545685, -0.31267726,  0.47010869],
         [ 1.39482987, -0.

In [25]:
a[0, 2]

array([[ 0.5955812 ,  0.1459882 , -1.41524583],
       [-1.02023904, -2.33976778, -1.52018717]])